apache/dubbo-kubernetes

- README.md
> Fix #5: Updated `Service` Typo in README.md

- app/dubboctl/cmd/build.go
- app/dubboctl/cmd/deploy.go
- app/dubboctl/internal/dubbo/deploy.tpl
- app/dubboctl/internal/dubbo/deployer.go
- app/dubboctl/internal/dubbo/dubbo.go
> fix deploy and build

- ui/src/components/ServiceSearch.vue
- ui/src/store/index.js
fix: Fixes apache/dubbo-admin#1166
> fix:  Query condition prompt function reports error

- ui-vue3/package.json
- ui-vue3/yarn.lock
> fix: add dependency

- release/downloadDubbo.sh
- release/downloadDubboCtl.sh
- For https://github.com/apache/dubbo-kubernetes/issues/114
> feat: update realease shell scripts

- pkg/admin/cache/registry/universal/cache.go
- pkg/admin/cache/selector/application_selector.go
- pkg/admin/cache/selector/multi_selector.go
- pkg/admin/cache/selector/service_selector.go
Add support for selecting resource by service in admin cache, and optimized code structure.
XXXX
> feat: add support for cache selection by service

- pkg/admin/bootstrap.go
- pkg/admin/cache/README.md
- pkg/admin/cache/registry/extension.go
- pkg/admin/cache/registry/kube/registry.go
- pkg/admin/cache/registry/universal/registry.go
- pkg/admin/config/config.go
Add cache configuration reading and initialization process.
XXXX
> feat: impl cache bootstrap

- ui-vue3/src/layout/menu/layout_menu.vue
- ui-vue3/src/router/defaultRoutes.ts
fix problem about #143
刷新前：
刷新后
> fix refresh bug

- ui-vue3/src/App.vue
change progress style to black
resolve #169
> change progress style

- ui-vue3/package.json
- ui-vue3/src/api/mock/mockServiceDetail.ts
- ui-vue3/src/api/mock/mockServiceDistribution.ts
- ui-vue3/src/api/service/serviceDetail.ts
- ui-vue3/src/api/service/serviceDistribution.ts
- ui-vue3/src/base/i18n/zh.ts
- ui-vue3/src/views/resources/services/search.vue
- ui-vue3/src/views/resources/services/tabs/debug.vue
- ui-vue3/src/views/resources/services/tabs/detail.vue
- ui-vue3/src/views/resources/services/tabs/distribution.vue
- ui-vue3/vite.config.ts
- ui-vue3/yarn.lock
> Improve service pages

- ui-vue3/src/components/editor/MonacoEditor.ts
- ui-vue3/src/components/editor/MonacoEditor.vue
- ui-vue3/src/main.ts
- ui-vue3/src/views/resources/services/tabs/debug.vue
improve monaco-editor component
> improve monaco-editor component

- ui-vue3/src/layout/tab/layout_tab.vue
- ui-vue3/src/router/defaultRoutes.ts
- ui-vue3/src/views/resources/applications/index.vue
- ui-vue3/src/views/resources/applications/tabs/tab2.vue
- ui-vue3/src/views/resources/applications/tabs/tab3.vue
- ui-vue3/src/views/resources/services/search.vue
- ui-vue3/src/views/resources/services/tabs/debug.vue
> fix(#187): The tab layout make components be invoked much times

- ui-vue3/src/components/SearchTable.vue
- ui-vue3/src/views/resources/applications/index.vue
- ui-vue3/src/views/resources/applications/tabs/instance.vue
1. Remove the default table height.
2. Modify the width of the table columns on the instance tab page under the application, and display the columns as much as possible.
> improve table style

- .github/PULL_REQUEST_TEMPLATE.md
> chore: update pr templates

- ui-vue3/src/layout/index.vue
- ui-vue3/src/layout/tab/layout_tab.vue
- ui-vue3/src/router/defaultRoutes.ts
- ui-vue3/src/views/resources/instances/index.vue
1. use <Slot/> to add tabTitle for layout_tab_view
2. Fix instance module sorting bug
> add TabTitle

- api/system/v1alpha1/zone_insight_helpers.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/managers/apis/zone/zone_manager.go
- pkg/core/managers/apis/zone/zone_manager_suite_test.go
- pkg/core/managers/apis/zone/zone_manager_test.go
- pkg/core/managers/apis/zone/zone_validator.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/containerpatch_validator.go
- pkg/plugins/runtime/k8s/webhooks/policy_namespace_validator.go
- pkg/plugins/runtime/k8s/webhooks/service_validator.go
- pkg/plugins/runtime/k8s/webhooks/zone_validator.go
- test/app/consumer/deployment.yaml
- test/app/consumer/service.yaml
- test/app/provider/deployment.yaml
- test/app/provider/service.yaml
- test/app/provider/serviceaccount.yaml
> validator and mutator

- ui-vue3/src/api/mock/mockDestinationRule.ts
- ui-vue3/src/api/mock/mockDynamicConfig.ts
- ui-vue3/src/api/mock/mockTagRule.ts
- ui-vue3/src/api/mock/mockVirtualService.ts
- ui-vue3/src/api/service/traffic.ts
- ui-vue3/src/base/i18n/en.ts
- ui-vue3/src/base/i18n/zh.ts
- ui-vue3/src/components/SearchTable.vue
- ui-vue3/src/router/defaultRoutes.ts
- ui-vue3/src/views/traffic/destinationRule/index.vue
- ui-vue3/src/views/traffic/dynamicConfig/index.vue
- ui-vue3/src/views/traffic/routingRule/index.vue
- ui-vue3/src/views/traffic/tagRule/index.vue
- ui-vue3/src/views/traffic/virtualService/index.vue
> add traffic control pages

- ui-vue3/src/api/mock/mockInstance.ts
- ui-vue3/src/api/service/instance.ts
- ui-vue3/src/base/i18n/en.ts
- ui-vue3/src/base/i18n/zh.ts
- ui-vue3/src/router/defaultRoutes.ts
- ui-vue3/src/views/resources/instances/index.vue
- ui-vue3/src/views/resources/instances/tabs/configuration.vue
- ui-vue3/src/views/resources/instances/tabs/details.vue
- ui-vue3/src/views/resources/instances/tabs/monitor.vue
- ui-vue3/src/views/traffic/destinationRule/index.vue
- ui-vue3/src/views/traffic/destinationRule/tabs/YAMLView.vue
- ui-vue3/src/views/traffic/destinationRule/tabs/formView.vue
- ui-vue3/src/views/traffic/dynamicConfig/index.vue
- ui-vue3/src/views/traffic/dynamicConfig/tabs/YAMLView.vue
- ui-vue3/src/views/traffic/dynamicConfig/tabs/formView.vue
- ui-vue3/src/views/traffic/routingRule/index.vue
- ui-vue3/src/views/traffic/routingRule/tabs/YAMLView.vue
- ui-vue3/src/views/traffic/routingRule/tabs/formView.vue
- ui-vue3/src/views/traffic/tagRule/index.vue
- ui-vue3/src/views/traffic/tagRule/tabs/YAMLView.vue
- ui-vue3/src/views/traffic/tagRule/tabs/formView.vue
- ui-vue3/src/views/traffic/virtualService/index.vue
- ui-vue3/src/views/traffic/virtualService/tabs/YAMLView.vue
- ui-vue3/src/views/traffic/virtualService/tabs/formView.vue
**Task:**
1.    Completed the construction of all sub-module form view and YAML view pages under traffic monitoring
2.    Added corresponding i18n field
3.    Resource-instance module UI follow-up Resource-application, and completed configuration tab page construction
4.    Routes are added to the page
> Add corresponding tab(Form View Tab and YAML View Tab) for all routing modules under traffic control module.

- deploy/charts/admin/README.md
- deploy/charts/admin/README.md.gotmpl
- deploy/charts/admin/changelog/helm-chart.md.gotmpl
- deploy/charts/admin/values.schema.json
add charts changelog and json or gotmpl
> chore: add charts changelog and json or gotmpl

- .github/workflows/issue-comment.yml
- Add issue comment action
See: https://github.com/envoyproxy/gateway/blob/main/.github/workflows/issue-comment.yaml
> chore: add issue comment

- pkg/admin/model/application.go
- pkg/admin/service/application.go
make some minor adjustments to console application interface
> some minor adjustments to console application interface

- pkg/admin/handler/observability.go
- pkg/admin/model/observability.go
- pkg/admin/server/router.go
- pkg/admin/service/instance.go
add metrics detail for dubbo instance
- add /metrics-list for router
- add prometheus resolving
- add metrics support for dubbo-kubernetes
> feat: add metrics detail list for dubbo instance

- conf/dubbo-cp.yaml
- pkg/core/bootstrap/bootstrap.go
- pkg/core/registry/application_context.go
- pkg/core/registry/registry.go
- pkg/plugins/resources/traditional/plugin.go
- pkg/plugins/resources/traditional/store.go
> Involve the app context in the resource manager

- app/dubbo-ui/fs.go
Problem: we can't reload the page when the URL is not the default admin page. (Part of #482)
Resolve it by adapting Vue's HTML5 history mode, see: [Vue Documentation](https://v3.router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90).
- adapt Vue's HTML5 history mode
Run dubbo-cp and navigate to `http://localhost:8888/admin/traffic/routingRule/index` directly.
> fix(dubbo-ui): adapt Vue's HTML5 history mode

- .gitignore
- pkg/admin/handler/instance.go
- pkg/admin/handler/search.go
- pkg/admin/model/application.go
- pkg/admin/model/instance.go
- pkg/admin/service/instance.go
- pkg/core/managers/apis/dataplane/dataplane_manager.go
- improve the global search function
- correct the metadata field to `appName`
- merge some k8s fields into dataplane resource when run with `half` mode
> fix: improve the global search function and correct the metadata fields

- pkg/admin/handler/application.go
- pkg/admin/model/application.go
fix bugs:
1. get flowWeight's scope bug
2. get/put graySet' scope should be array
run dubbo-cp and call the httpapi
> [Admin]Fix: <GET>flowWeight's scope bug; <GET/PUT>graySet scope should be array

- api/mesh/v1alpha1/condition_route_helper.go
- app/dubbo-cp/dubbo-cp.yaml
- pkg/admin/handler/instance.go
Fix: disable instance traffic
run dubbo-cp, call api `http://localhost:8888/api/v1/instance/config/trafficDisable` to verify it
> [Dubbo-Admin]Fix: disable instance traffic

- app/dubbo-cp/dubbo-cp.yaml
- pkg/admin/handler/overview.go
- pkg/config/admin/config.go
- pkg/config/app/dubbo-cp/config.go
- pkg/config/core/resources/store/config.go
- pkg/config/plugins/runtime/config.go
- pkg/core/bootstrap/bootstrap.go
> fix: load config bugs; add config explanation
